# Generated by Django 3.2 on 2022-04-20 13:09

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('slug', models.SlugField(max_length=12, primary_key=True, serialize=False, unique=True, verbose_name='Page code')),
                ('title', models.CharField(max_length=250)),
                ('text_content', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255)),
                ('link', models.TextField(blank=True)),
                ('link_title', models.CharField(blank=True, max_length=250)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Ready to Send')], default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
