# Generated by Django 3.2 on 2022-05-14 12:21

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True, verbose_name='Page code')),
                ('title', models.CharField(max_length=250)),
                ('text_content', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255)),
                ('link', models.TextField(blank=True)),
                ('link_title', models.CharField(blank=True, max_length=250)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Ready to Send')], default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_page', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ViewerAccess',
            fields=[
                ('shown_name', models.CharField(max_length=100, verbose_name='Your name (as it will appear to viewer)')),
                ('first_name', models.CharField(max_length=100, verbose_name='The name of the viewer you are sending this to')),
                ('viewer_email', models.EmailField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('allowed_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='out_app.page', verbose_name='Page you would like the recipient to see')),
            ],
        ),
    ]
