# Generated by Django 3.2 on 2022-03-18 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('out_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='photo',
            new_name='photo_content',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='video',
            new_name='video_content',
        ),
    ]
