# Generated by Django 3.2 on 2022-03-25 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('out_app', '0002_auto_20220318_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='page_code',
            new_name='slug',
        ),
    ]
