# Generated by Django 3.2 on 2022-04-20 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('out_app', '0002_auto_20220420_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vieweraccess',
            old_name='viewer_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='vieweraccess',
            old_name='viewer_name',
            new_name='first_name',
        ),
    ]
