# Generated by Django 3.2 on 2022-04-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('out_app', '0003_auto_20220420_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vieweraccess',
            name='id',
        ),
        migrations.AlterField(
            model_name='vieweraccess',
            name='email',
            field=models.EmailField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
