# Generated by Django 3.2 on 2022-04-06 12:16

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('out_app', '0003_rename_page_code_page_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='link',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='photo_content',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='page',
            name='video_content',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
    ]
