# Generated by Django 3.2 on 2022-05-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('out_app', '0003_alter_page_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='link',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
