# Generated by Django 3.2 on 2022-04-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('out_app', '0004_auto_20220420_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vieweraccess',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='The name of the viewer you are sending this to'),
        ),
        migrations.AlterField(
            model_name='vieweraccess',
            name='shown_name',
            field=models.CharField(max_length=100, verbose_name='Your name (as it will appear to viewer)'),
        ),
    ]
