# Generated by Django 3.2 on 2022-04-06 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('out_app', '0004_auto_20220406_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_name', models.TextField(blank=True, max_length=100)),
                ('viewer_email', models.EmailField(max_length=100)),
                ('viewer_creator', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='page_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
