# Generated by Django 3.2 on 2022-04-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('out_app', '0005_viewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewer',
            name='viewer_name',
            field=models.TextField(max_length=100),
        ),
    ]
