# Generated by Django 3.2 on 2022-04-26 11:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('out_app', '0005_auto_20220425_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255),
        ),
    ]
