# Generated by Django 3.2 on 2022-05-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('out_app', '0005_alter_page_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='link',
            field=models.CharField(blank=True, max_length=500, verbose_name="Link - <a href='{% url 'resources' %}'>Suggested links</a>"),
        ),
    ]
