# Generated by Django 3.2 on 2022-05-01 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('out_app', '0006_alter_page_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vieweraccess',
            name='allowed_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='out_app.page', verbose_name='Page you would like the recipient to see'),
        ),
    ]
