# Generated by Django 3.2 on 2022-04-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('out_app', '0007_alter_viewer_viewer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='link_title',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
