# Generated by Django 3.2 on 2022-04-12 16:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('out_app', '0008_page_link_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='photo_content',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255),
        ),
    ]
