# Generated by Django 3.2 on 2022-05-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('out_app', '0008_rename_email_vieweraccess_viewer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(primary_key=True, serialize=False, unique=True, verbose_name='Page code'),
        ),
    ]
