# Generated by Django 3.2 on 2022-04-13 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('out_app', '0009_alter_page_photo_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewer',
            name='viewer_creator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='page_creator', to=settings.AUTH_USER_MODEL, verbose_name='My name (as it will appear to viewer)'),
        ),
    ]
