# Generated by Django 3.2 on 2022-04-13 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('out_app', '0010_alter_viewer_viewer_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewer',
            name='shown_name',
            field=models.CharField(default=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL), max_length=100, verbose_name='My name (as it will appear to viewer)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewer_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='viewer',
            name='viewer_creator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
