# Generated by Django 3.2 on 2022-04-15 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('out_app', '0012_alter_page_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={},
        ),
        migrations.RemoveField(
            model_name='page',
            name='date',
        ),
    ]
