# Generated by Django 3.2 on 2022-04-15 15:00

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('out_app', '0013_auto_20220415_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='creator',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='viewer_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
