# Generated by Django 3.2 on 2022-04-17 13:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('out_app', '0015_alter_page_photo_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='video_content',
        ),
        migrations.AlterField(
            model_name='page',
            name='photo_content',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
