# Generated by Django 3.2 on 2022-04-18 10:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('out_app', '0017_alter_page_photo_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='photo_content',
        ),
        migrations.AddField(
            model_name='page',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
