# Generated by Django 3.2 on 2022-04-18 10:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('out_app', '0018_auto_20220418_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
    ]
