# Generated by Django 3.2 on 2022-04-18 11:36

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('out_app', '0020_alter_page_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewer',
            old_name='viewer_creator',
            new_name='related_creator',
        ),
        migrations.AlterField(
            model_name='page',
            name='creator',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='related_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='viewer',
            name='shown_name',
            field=models.CharField(max_length=100, verbose_name='My name (as it will appear to viewer)'),
        ),
    ]
