# Generated by Django 3.2 on 2022-04-20 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('out_app', '0022_alter_page_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Viewer',
        ),
    ]
